### ISSUE TITLE
Can it drive multiple Chrome at the same time?

### ISSUE THREAD

**Issue by pxpwoa** [marty90/PyChromeDevTools#10]
Sometimes, I want to visit various pages at the same time.

**Comment by marty90** [comment]
You can create a second tab issuing:
`new_tab = chrome.Target.createTarget(url="http://www.example.com")`
and then controlling it with:
```
targetID = new_tab ["result"]["targetId"][1:-1]
chrome_new_tab=PyChromeDevTools.ChromeInterface()
chrome_new_tab.connect_targetID(targetID)
```
and navigate:
`chrome_new_tab.Page.navigate(url="http://www.google.com/")`

**Comment by pxpwoa** [comment]
So Cool!!!
