### ISSUE TITLE
Is it possible to get websocket data?

### ISSUE THREAD

**Issue by rightx2** [marty90/PyChromeDevTools#11]
With Chrome in general, I can see the websocket data from `Chrome dev tools - network tab - websocket request - Frame tab`.

Is it possible to get these websocket data via `PyChromeDevTools` If i go to the url where using websocket?

**Comment by marty90** [comment]
You can manually connect to Chrome and download all the information and parse it on your own.
However, PyChromeDevTools does it for you and hides nothing - all messages are interpreted as JSON are provided to you.
