### ISSUE TITLE
If I want to fetch real-time http or https traffic

### ISSUE THREAD

**Issue by ldbfpiaoran** [marty90/PyChromeDevTools#14]
If I want to fetch real-time http or https traffic, but create a new tag, I can't get the traffic of the new tag using chrome.wait_message()

chrome = ChromeInterface()
chrome.Network.enable()
chrome.Page.enable()

count = 0 
while True:
    messages = chrome.wait_message()

    if messages != None:

        try:
            print(messages["params"]["response"]["url"])
        except:
            pass

**Comment by marty90** [comment]
Sorry cuijianxiong. I didn't get the question :(

**Comment by cuijianxiong** [comment]
think  I only want get event  when  chrome create new tab.and i use websocket to connect it,but I did not find the interface about create new tab.

**Comment by ldbfpiaoran** [comment]
@marty90  think I only want get event when chrome create new tab.and i use websocket to connect it,but I did not find the interface about create new tab.
