### ISSUE TITLE
Catch Ajax Request

### ISSUE THREAD

**Issue by Rimander** [marty90/PyChromeDevTools#18]
How can i catch ajax request?
Example: Google Maps

**Comment by miiow-cxt** [comment]
chrome = PyChromeDevTools.ChromeInterface()
chrome.Network.enable()
chrome.Page.enable()

chrome.Page.navigate(url="https://www.baidu.com/")
event,messages=chrome.wait_event("Page.frameStoppedLoading", timeout=60)

for m in messages:
    if "method" in m and m["method"] == "Network.responseReceived":
        try:
            url=m["params"]["response"]["url"]
            print (url)
            reqid = m['params']['requestId']
            print(chrome.Network.getResponseBody(requestId=reqid))              
            print("reqid: ", reqid)
        except:
            pass

**Comment by miiow-cxt** [comment]
> chrome = PyChromeDevTools.ChromeInterface()
chrome.Network.enable()
chrome.Page.enable()

chrome.Page.navigate(url="https://www.baidu.com/")
event,messages=chrome.wait_event("Page.frameStoppedLoading", timeout=60)

for m in messages:
    if "method" in m and m["method"] == "Network.responseReceived":
        try:
            url=m["params"]["response"]["url"]
            print (url)
            reqid = m['params']['requestId']
            print(chrome.Network.getResponseBody(requestId=reqid))              
            print("reqid: ", reqid)
        except:
            pass

**Comment by gongke-cxt** [comment]
`
chrome = PyChromeDevTools.ChromeInterface()
chrome.Network.enable()
chrome.Page.enable()

chrome.Page.navigate(url="https://www.baidu.com/")
event,messages=chrome.wait_event("Page.frameStoppedLoading", timeout=60)

for m in messages:
    if "method" in m and m["method"] == "Network.responseReceived":
        try:
            url=m["params"]["response"]["url"]
            print (url)
            reqid = m['params']['requestId']
            print(chrome.Network.getResponseBody(requestId=reqid))              
            print("reqid: ", reqid)
        except:
            pass
`

**Comment by Rimander** [comment]
Thanks
