### ISSUE TITLE
Cannot Make PDF Landscape or Change Size of Screenshots

### ISSUE THREAD

**Issue by AlisterC93** [marty90/PyChromeDevTools#3]
Please see title. I know these features are experimental, I was wondering if more information could be given, such as whether these will be included in the final version and if so, what would the estimated time of their completion be?

Thank you, I appreciate your work.

**Comment by marty90** [comment]
Dear AlisterC93,
PyChromeDevTools is just a wrapper for Chrome DevTools Protocol.
Thus, the available features only depend on that.

BTW: I noticed that so far Page.printToPDF doesn't work, but Page.captureScreenshot worked for me.

**Comment by marty90** [comment]
I investigated and, when invoking Page.printToPDF, under the hood Chrome answers with an error message, like:
`{"error":{"code":-32601,"message":"'Page.printToPDF' wasn't found"},"id":23}`

**Comment by AlisterC93** [comment]
I can get Page.printToPDF working, as with screenshots. My apologies I wasn't sure if it was the wrapper or the devtools themselves causing the error. I'll be sure to update with progress when I have more time to work on the issue.

**Comment by ghost** [comment]
> I can get Page.printToPDF working, as with screenshots. My apologies I wasn't sure if it was the wrapper or the devtools themselves causing the error. I'll be sure to update with progress when I have more time to work on the issue.

Can you please tell me how did you make it work?
I also have an error calling "Page.printToPDF":

`{"code":-32601,"message":"'Page.printToPDF' wasn't found"}`

**Comment by marty90** [comment]
Looking around (e.g. https://github.com/puppeteer/puppeteer/issues/6220), it seems `printToPDF` only works in **headless** mode. Did you try it?
