### ISSUE TITLE
Puplish to PyPi

### ISSUE THREAD

**Issue by AKuederle** [marty90/PyChromeDevTools#4]
Hey,

I just wanted to ask, if it is possible for you to publish this package to PyPi? This would ease the installation process. As you have already a setup.py file, this should not be to complicated.

**Comment by marty90** [comment]
It sounds good! But I want to test it for a couple of weeks before putting it on pip to have a reliable version .

**Comment by andresriancho** [comment]
Almost a year has passed, maybe it is time to publish it?

I'm writing web crawler using chrome for https://github.com/andresriancho/w3af/ and it would be easier for my users to install from pypi.

**Comment by AKuederle** [comment]
@marty90 If you need any help with that let me know! The only thing you have to do is to create an account on PyPi, which can be to upload the package. Everything else can be outsourced to willing contributers.

**Comment by marty90** [comment]
Thank you I think this weekend I have time to do this. In case I need help, I ll notice you :)

**Comment by marty90** [comment]
I published it to PIP ;)
Let me known if I did something wrong.
Try:
```
pip install PyChromeDevTools
```

**Comment by AKuederle** [comment]
Awesome! Looks good! From my side this issue can be closed!

**Comment by marty90** [comment]
Well ;)
