### ISSUE TITLE
How does one start a new context in chrome via Target.createBrowserContext ?

### ISSUE THREAD

**Issue by GuacheSuede** [marty90/PyChromeDevTools#7]
Question is title. Thanks

**Comment by marty90** [comment]
This module is completely agnostic with respect to the functions of the chrome remote interface. For an explanation of its functionalities please refer to the official documentation.

**Comment by GuacheSuede** [comment]
Thanks Marty, how would i tie a callback function to an event ? 
eg .
Page.onLoadFired = loadEventFunction

**Comment by marty90** [comment]
Unfortunately it is not possible so far. The best you can do is to wait for an event explicitly using the waitevent function .
