### ISSUE TITLE
Can it work with chromedriver and selenium?

### ISSUE THREAD

**Issue by pxpwoa** [marty90/PyChromeDevTools#9]
The tool  work well when I use it to scrapy the AJAX web.  However, I have to click  links in the ajax page to load the data I needed. So, I wonder whether there is a way to automatically navigate the page， like  what chromedriver and selenium  do.

**Comment by marty90** [comment]
Hello,
this question is about the [ChromeDevTool Protocol](https://chromedevtools.github.io/devtools-protocol).

In any case, it allows to send clicks to the browser using the [Input class ](https://chromedevtools.github.io/devtools-protocol/tot/Input/).

**Comment by marty90** [comment]
More details [here](https://groups.google.com/forum/#!topic/chrome-debugging-protocol/9rxkDBRZc24).

**Comment by pxpwoa** [comment]
Thanks, it really do a favor for me.
